[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.11.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/size"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  name = "github.com/alicebob/miniredis"
  version = "2.4.4"

[[constraint]]
  name = "github.com/chartmuseum/storage"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/chartmuseum/auth"
  version = "0.1.0"
