name: build-pr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.2'
      - name: download dependencies
        run: make bootstrap
      - name: run unit tests
        run: make test
      - name: build binary
        run: make build-linux
      - name: run acceptance tests
        run: make acceptance
      - name: upload coverage report
        uses: actions/upload-artifact@master
        with:
          name: chartmuseum-coverage-report-${{ github.sha }}
          path: .cover/
        if: always()
      - name: upload acceptance test report
        uses: actions/upload-artifact@master
        with:
          name: chartmuseum-acceptance-report-${{ github.sha }}
          path: .robot/
        if: always()

